import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Crew Hub",
  description: "Generated by create next app",
  keywords: ["team", "access control"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="min-h-screen bg-slate-950 text-slate-500">{children}</body>
    </html>
  );
}
